### ISSUE TITLE
Predicate - проверка логического условия - что проверяется здесь?

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/Avito-SQL-JdbcTemplate#3]
https://github.com/Artyom16RUS/Avito-SQL-JdbcTemplate/blob/c83ddbc799b2dce264cb889605dee127367a6559/src/main/java/ru/itpark/service/HouseServices.java#L23-L27

**Comment by Artyom16RUS** [comment]
Это случайно попало с комимтом. Я сделал работу потом решил поэксперементировать и забыл убрать.
