### ISSUE TITLE
Как объеденить в один метод

### ISSUE THREAD

**Issue by Artyom16RUS** [Artyom16RUS/Avito-SQL-JdbcTemplate#6]
https://github.com/Artyom16RUS/Avito-SQL-JdbcTemplate/blob/4d64acec763ff54a47b2918f69b15dfc095a4db3/src/main/java/ru/itpark/service/HouseService.java#L62-L72

Как можно два метода объеденить в один. Их только различает методы _getMetro_ и _getDistrict_ который передает параметр. Создать один метод и передавть в него по ссылке другой у меня не получилось.

**Comment by coursar** [comment]
Сделайте третий: `sortBy(Comparator<House> comparator)` и в него передавайте лямбду
